extends:
  - airbnb-base
  - prettier
plugins: [prettier]
rules:
  linebreak-style:
    - 0
    - windows
  prettier/prettier: error
overrides:
  files: ["*-test.js", "*.spec.js"]
  rules:
    no-unused-expressions: off
    new-cap: off
    no-undef: off
